name: Deploy-Azure-Bicep-and-App-Code

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  # NOMES CORRIGIDOS PARA CORRESPONDER AO SEU PORTAL AZURE
  RESOURCE_GROUP: rg-github-actions-workflow
  WEBAPP_NAME: meu-app-jl-workflow-enis

jobs:
  preview-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checks-out your repository
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: Azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Garante que o Grupo de Recursos exista na localização correta
      - name: Create or Update Azure Resource Group
        uses: Azure/cli@v1.0.6
        with:
          inlineScript: |
            az group create -n $RESOURCE_GROUP -l "Brazil South"

      # Previsualiza as mudanças da infraestrutura
      - name: Preview Changes from Bicep
        uses: Azure/deployment-what-if-action@v1.0.0
        with:
          subscription: ${{ secrets.SUBSCRIPTION_ID  }}
          resourceGroup: $RESOURCE_GROUP
          templateFile: 01-bicep-webapp/webapp-linux.bicep
          additionalParameters: webAppName=$WEBAPP_NAME

      # Implanta a infraestrutura (Web App)
      - name: Deploy Bicep Infrastructure to Azure
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP }}
          template: 01-bicep-webapp/webapp-linux.bicep
          parameters: webAppName=${{ env.WEBAPP_NAME }}
          failOnStdErr: false

      # Implanta o CÓDIGO da aplicação no Web App
      - name: Deploy application code to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.WEBAPP_NAME }} # <-- Agora vai usar 'meu-app-jl-workflow-enis'
          slot-name: 'production'
          package: .
